### ISSUE TITLE
Drop Stacey

### ISSUE THREAD

**Issue by raphaelbastide** [libreobjet/libreobjet.org#21]
Stacey sounds [inactive](https://github.com/kolber/stacey/commits/master). Let’s try to find another CMS.

To try:

### [Pelican](https://github.com/getpelican/pelican/)

- Needs to be compiled (Python)
- Search engine planned (?)
- [tags](http://docs.getpelican.com/en/3.3.0/settings.html#tag-cloud)
- GPL

### [spress](http://spress.yosymfony.com/)

- PHP
- tags
- MIT

### More

http://staticsitegenerators.net/

**Comment by raphaelbastide** [comment]
New version in progress using http://getgrav.org/

**Comment by xuv** [comment]
I'm just realizing that Grav is not a static website generator.
I've always preferred static websites for LO as it does not allow a webserver to "read" the doc.
I somehow envision LO website as something you can drop on a USB key and just browse through.
Something to have in the back of your pocket. I though Grav produced this. But it's not the case.
I've been using Jekyll for a while now. Will see if I can use that instead. There will be trade offs. Some functions might not be available. But will see.

**Comment by xuv** [comment]
Moved to Jekyll.

**Comment by raphaelbastide** [comment]
Not sure Jekyll lets you have images within folders, outside of the assets directory, but
1. Maybe it has changed
2. Maybe a patch / plugin can solve that

**Comment by xuv** [comment]
1. It has changed. ;)

**Comment by xuv** [comment]
If you want to check the temporary version: http://libreobjet.github.io/

**Comment by raphaelbastide** [comment]
Wow that looks much simpler and robust!
What’s the plan for the design?

**Comment by xuv** [comment]
Yes. The interface. So far, I'm keeping the design you did. I like it. Although I want to improve the first page (add more info, maybe a mention of the license plus other things). But I'm a bit stuck with the object detail page. Don't know what to do with all these images. :)

**Comment by xuv** [comment]
I know this issue is closed, but I wanted to add those static site generators:
 - https://github.com/static-dev/spike
 - https://github.com/gatsbyjs/gatsby
