### ISSUE TITLE
Search Function Error

### ISSUE THREAD

**Issue by Krands** [libreobjet/libreobjet.org#25]
Bonjour,

Dans la page *Recherche*, il n'est pas possible d'en effectuer une car il y a une erreur.
Voici ce que ça dit : 
`An exception has been thrown during the rendering of a template ("Unable to parse string: Unable to parse line 1 (Free Art License 1.3).").`

**Comment by raphaelbastide** [comment]
Duplicate https://github.com/libreobjet/libreobjet.org/issues/10
(merci)
